# Generated by Django 5.2.17 on 2026-08-25 16:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. High Overdue Risk Alert', max_length=160)),
                ('metric_id', models.CharField(help_text='e.g. total_overdue_receivables, recovery_rate', max_length=80)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than (>)'), ('gte', 'Greater Than or Equal (>=)'), ('lt', 'Less Than (<)'), ('lte', 'Less Than or Equal (<=)'), ('eq', 'Equal (==)'), ('neq', 'Not Equal (!=)')], default='gt', max_length=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('currency', models.CharField(default='REPORTING', max_length=10)),
                ('filters_config', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('in_app', 'In-App Alert Notification'), ('email', 'Email Alert'), ('push', 'Push Notification')], default='in_app', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Portfolio Risk, Monthly Collections', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this dashboard loads first')),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Grid coordinates and layout metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(default='metric', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metric_id', models.CharField(help_text='Central Metric ID from MetricRegistry', max_length=80)),
                ('data_source', models.CharField(default='loans', help_text='loans, payments, people, reminders, audit', max_length=50)),
                ('filters_config', models.JSONField(blank=True, default=dict, help_text='Dynamic AST filter tree')),
                ('date_range', models.CharField(default='last_30_days', max_length=50)),
                ('group_by', models.CharField(blank=True, max_length=50)),
                ('sort_by', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='REPORTING', max_length=10)),
                ('visualization_type', models.CharField(choices=[('kpi_card', 'KPI Stat Card'), ('line_chart', 'Trend Line Chart'), ('area_chart', 'Cash Flow Area Chart'), ('bar_chart', 'Grouped Bar Chart'), ('stacked_bar', 'Stacked Composition Bar'), ('donut_chart', 'Donut Share Chart'), ('pie_chart', 'Pie Chart'), ('heatmap', 'Density Heatmap'), ('waterfall', 'Net Waterfall Chart'), ('progress_bar', 'Progress Meter'), ('table', 'Detail Data Table'), ('pivot_table', '2D Pivot Matrix Table')], default='kpi_card', max_length=30)),
                ('grid_position', models.JSONField(blank=True, default=dict, help_text='x, y, w, h grid coordinates')),
                ('refresh_interval', models.IntegerField(default=0, help_text='Auto-refresh seconds (0 = manual)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.customdashboard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('loans', 'Loans & Lending Ledger'), ('borrowing', 'Borrowing Obligations Ledger'), ('payments', 'Repayment & Collection Transactions'), ('people', 'People & Counterparty Directory'), ('reminders', 'Reminders & Notifications'), ('statements', 'Digital Statements Audit'), ('audit', 'Audit Ledger Activity')], default='loans', max_length=40)),
                ('selected_fields', models.JSONField(default=list, help_text='List of column field keys to display')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='Aggregated metrics like SUM(outstanding)')),
                ('filters_config', models.JSONField(blank=True, default=dict, help_text='Dynamic AST filter tree')),
                ('group_by', models.CharField(blank=True, help_text='e.g. person, currency, month, status', max_length=60)),
                ('pivot_columns', models.CharField(blank=True, help_text='Secondary group-by for 2D pivot matrices', max_length=60)),
                ('sort_by', models.CharField(default='created_at', max_length=60)),
                ('sort_order', models.CharField(default='desc', max_length=10)),
                ('visualization_type', models.CharField(default='table', max_length=40)),
                ('visibility', models.CharField(choices=[('private', 'Private (Owner Only)'), ('workspace', 'Workspace Members'), ('shared', 'Shared via Link/Export')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily Digest'), ('weekly', 'Weekly Summary'), ('monthly', 'Monthly Financial Report'), ('quarterly', 'Quarterly Portfolio Review')], default='monthly', max_length=20)),
                ('delivery_channel', models.CharField(choices=[('in_app', 'In-App Notification & Download'), ('email', 'Email PDF/Excel Attachment'), ('download', 'Direct Ready Download')], default='in_app', max_length=20)),
                ('export_format', models.CharField(default='PDF', max_length=10)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses or user IDs')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
                ('saved_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='analytics.savedreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('VOID', 'Payment Voided/Reversed'), ('EXPORT', 'Data/Report Exported'), ('GENERATE', 'Statement Generated'), ('LOGIN', 'User Logged In'), ('SECURITY_CHANGE', 'Security/Profile Setting Changed')], max_length=25)),
                ('module', models.CharField(choices=[('LOANS', 'Lending Ledger'), ('BORROWING', 'Borrowing Ledger'), ('PAYMENTS', 'Repayments & Collections'), ('PEOPLE', 'Counterparty Contacts'), ('STATEMENTS', 'Digital Statements'), ('REPORTS', 'Analytics & Reports'), ('SETTINGS', 'Admin & Settings'), ('AUTH', 'Authentication')], max_length=25)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('target_reference', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField(blank=True)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'module', 'action'], name='analytics_a_user_id_58ee18_idx'), models.Index(fields=['timestamp'], name='analytics_a_timesta_0986be_idx')],
            },
        ),
    ]
