# Generated by Django 5.2.17 on 2026-08-25 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'In-App Alert'), ('email', 'Email Notification'), ('push', 'Push Notification (FCM/APNs)'), ('whatsapp', 'WhatsApp (Share/Deep Link)')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('deep_link', models.CharField(blank=True, help_text='Relative URL to loan or payment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('7_days_before', '7 Days Before Due Date'), ('3_days_before', '3 Days Before Due Date'), ('1_day_before', '1 Day Before Due Date'), ('due_today', 'Due Today Reminder'), ('overdue', 'Overdue Follow-up Reminder')], max_length=30)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent / Delivered'), ('suppressed', 'Suppressed (Loan Settled / Cancelled)')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.loan')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
