# Generated by Django 5.2.17 on 2026-08-25 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(help_text='e.g. STMT-LG-2026-0001-01', max_length=60, unique=True)),
                ('canonical_data_snapshot', models.JSONField(help_text='Canonical JSON snapshot of loan, person, balance, and repayment ledger')),
                ('sha256_hash', models.CharField(help_text='Cryptographic SHA-256 integrity hash', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='loans.loan')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
