# Generated by Django 5.2.17 on 2026-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_currency',
            field=models.CharField(default='INR', help_text='Configurable reporting/base currency', max_length=10),
        ),
    ]
