# Generated by Django 5.2.17 on 2026-08-25 11:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_reference', models.CharField(help_text='Unique reference code (e.g. LG-2026-0001)', max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('lent', 'Money Lent (Given)'), ('borrowed', 'Money Borrowed (Received)')], default='lent', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date_given', models.DateField(help_text='Date money was handed over/transferred')),
                ('due_date', models.DateField(blank=True, help_text='Agreed repayment target date', null=True)),
                ('interest_model', models.CharField(choices=[('none', 'No Interest (Principal Only)'), ('simple_annual', 'Simple Annual Rate (%)'), ('monthly_rate', 'Monthly Rate (%)'), ('fixed_fee', 'Fixed Fee Amount')], default='none', max_length=30)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual or Monthly percentage rate if applicable', max_digits=6)),
                ('fixed_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed one-time borrowing fee if applicable', max_digits=12)),
                ('purpose', models.CharField(blank=True, help_text='Short description of what the money was lent for', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Private audit notes')),
                ('status', models.CharField(choices=[('OPEN', 'Open (No Repayments)'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid / Settled'), ('WRITTEN_OFF', 'Written Off (Defaulted)'), ('CANCELLED', 'Cancelled / Voided')], default='OPEN', max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='people.person')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-date_given', '-created_at'],
            },
        ),
    ]
