# Generated by Django 5.2.17 on 2026-08-25 13:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='FX rate: 1 original_currency = X reporting_currency', max_digits=18),
        ),
        migrations.AddField(
            model_name='loan',
            name='fx_rate_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='reporting_currency',
            field=models.CharField(default='INR', help_text='Base/Reporting currency at origination', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='reporting_principal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal amount converted to reporting_currency', max_digits=16),
        ),
        migrations.AlterField(
            model_name='loan',
            name='currency',
            field=models.CharField(default='INR', help_text='Original transaction currency', max_length=10),
        ),
    ]
