# Generated by Django 5.2.17 on 2026-08-25 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_exchange_rate_loan_fx_rate_date_and_more'),
        ('people', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['created_by', 'direction', 'status'], name='loans_loan_created_524648_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['person', 'direction'], name='loans_loan_person__24b2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='loans_loan_due_dat_1042a5_idx'),
        ),
    ]
