# Generated by Django 5.2.17 on 2026-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_loans_loan_created_524648_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='direction',
            field=models.CharField(choices=[('lent', 'Money Lent (Given / Receivable)'), ('borrowed', 'Money Borrowed (Received / Payable)'), ('LENDING', 'Money Lent (Given / Receivable)'), ('BORROWING', 'Money Borrowed (Received / Payable)')], default='lent', max_length=20),
        ),
    ]
