# Generated by Django 5.2.17 on 2026-08-25 11:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(help_text='Date repayment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash in Hand'), ('upi_bank_transfer', 'UPI / Direct Bank Transfer / NEFT / IMPS'), ('card', 'Debit / Credit Card'), ('check', 'Cheque'), ('other', 'Other Transfer Method')], default='cash', max_length=30)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, Cheque No, or Bank Reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Set to true if payment is reversed/cancelled')),
                ('void_reason', models.TextField(blank=True, help_text='Audit explanation for payment reversal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
