# Generated by Django 5.2.17 on 2026-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_currency_payment_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash in Hand'), ('upi_bank_transfer', 'UPI / Direct Bank Transfer / NEFT / IMPS'), ('card', 'Debit / Credit Card'), ('check', 'Cheque'), ('other', 'Other Transfer Method'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI Payment'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='cash', max_length=30),
        ),
    ]
