# Generated by Django 5.2.17 on 2026-08-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IN', 'India'), ('GB', 'United Kingdom'), ('US', 'United States'), ('EU', 'European Union (SEPA)'), ('AE', 'United Arab Emirates'), ('CA', 'Canada'), ('AU', 'Australia'), ('OTHER', 'International / Other')], default='IN', max_length=10)),
                ('bank_name', models.CharField(help_text='Name of the financial institution', max_length=150)),
                ('account_holder_name', models.CharField(help_text='Beneficiary name on bank record', max_length=150)),
                ('account_number', models.CharField(help_text='Bank Account Number or IBAN', max_length=64)),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Savings Account'), ('current', 'Current / Checking Account'), ('business', 'Business Account'), ('salary', 'Salary Account'), ('other', 'Other')], default='savings', max_length=30)),
                ('is_primary', models.BooleanField(default=False, help_text='Default disbursement account for this contact')),
                ('ifsc_code', models.CharField(blank=True, help_text='11-digit IFSC code for India (e.g. HDFC0001234)', max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='Virtual Payment Address / UPI ID (e.g. name@okhdfcbank)', max_length=100)),
                ('sort_code', models.CharField(blank=True, help_text='6-digit UK Sort Code (e.g. 20-45-77)', max_length=20)),
                ('routing_number', models.CharField(blank=True, help_text='9-digit ABA Routing Transit Number for USA', max_length=20)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number (IBAN)', max_length=40)),
                ('swift_bic', models.CharField(blank=True, help_text='8 or 11 character SWIFT/BIC code', max_length=20)),
                ('transit_number', models.CharField(blank=True, help_text='5-digit Branch Transit Number', max_length=10)),
                ('institution_number', models.CharField(blank=True, help_text='3-digit Financial Institution Number', max_length=10)),
                ('bsb_number', models.CharField(blank=True, help_text='6-digit Bank State Branch (BSB) number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='people.person')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
